### ISSUE TITLE
action buckets に複数の action を定義できない

### ISSUE THREAD

**Issue by mochipon** [trema/trema-edge#84]
action buckets に複数の action を定義できないように見えます。
## トポロジ

``` ruby
# Trema switch definition
trema_switch( "sw1" ) {
  datapath_id "0x111"
}

# Host definition
vhost ( "host1" ) {
  ip "192.168.0.1"
  netmask "255.255.255.0"
}
vhost ( "host2" ) {
  ip "192.168.0.2"
  netmask "255.255.255.0"
}
vhost ( "host3" ) {
  ip "192.168.0.3"
  netmask "255.255.255.0"
}
vhost ( "host4" ) {
  ip "192.168.0.4"
  netmask "255.255.255.0"
}

# Link definition
link "sw1", "host1"
link "sw1", "host2"
link "sw1", "host3"
link "sw1", "host4"
```
## スイッチ

src/examples/openflow_message/group-mod.rb をベースに以下のように定義

``` ruby
  def switch_ready datapath_id
    bucket1 = Bucket.new(
      weight: 1,
      watch_port: 2,
      actions: [
        SetField.new( action_set: [
          EthDst.new( mac_address: Mac.new( "00:00:5E:00:42:01" ) ),
          EthSrc.new( mac_address: Mac.new( "00:00:5E:00:42:02" ) )
        ] ),
        SendOutPort.new(
          port_number: 2,
          max_len: OFPCML_NO_BUFFER
      )]
    )
    bucket2 = Bucket.new(
      weight: 1,
      watch_port: 3,
      actions: [
#        SetField.new( action_set: [
#          EthDst.new( mac_address: Mac.new( "00:00:5E:00:42:03" ) ),
#          EthSrc.new( mac_address: Mac.new( "00:00:5E:00:42:04" ) )
#        ] ),
        SendOutPort.new(
          port_number: 3,
          max_len: OFPCML_NO_BUFFER
      )]
    )
    bucket3 = Bucket.new(
      weight: 1,
      watch_port: 4,
      actions: [
        SetField.new( action_set: [
          EthDst.new( mac_address: Mac.new( "00:00:5E:00:42:05" ) ),
          EthSrc.new( mac_address: Mac.new( "00:00:5E:00:42:06" ) )
        ] ) ]
#        SendOutPort.new(
#          port_number: 4,
#          max_len: OFPCML_NO_BUFFER
#      )]
    )

    send_group_mod_add(
      datapath_id,
      type: OFPGT_SELECT,
      group_id: 100,
      buckets: [ bucket1, bucket2, bucket3 ]
    )

    send_group_desc_multipart_request datapath_id

    action = GroupAction.new( group_id: 100 )
    ins = Instructions::ApplyAction.new( actions: [ action ] )
    send_flow_mod_add(
      datapath_id,
      match: Match.new( :in_port => 1 ),
      instructions: [ ins ]
    )
  end
```
## 実行結果

```
datapath_id: 0x111
transaction_id: 0x4f3c0005
type: 1
flags: 0
group_id: 100
  type: 1
  bucket:
    weight: 1
    watch_port: 2
    watch_group: 0
    action: Trema::Actions::SetField
  bucket:
    weight: 1
    watch_port: 3
    watch_group: 0
    SendOutPort:
      port_number: 3
      max_len: 65535
  bucket:
    weight: 1
    watch_port: 4
    watch_group: 0
    action: Trema::Actions::SetField
```
